"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.inputType = void 0;
var inputType;
(function (inputType) {
    inputType["AREA"] = "area";
    inputType["DATE"] = "date";
    inputType["LOCATION"] = "location";
    inputType["NUMBER"] = "number";
    inputType["OPTIONS"] = "options";
    inputType["PASSWORD"] = "password";
    inputType["RADIO"] = "radio";
    inputType["TEXT"] = "text";
    inputType["TIME"] = "time";
    inputType["PHONE"] = "phone";
    inputType["ABRCHECKBOX"] = "abr";
    inputType["EMAIL"] = "email";
    inputType["CHECKBOX"] = "checkbox";
    inputType["PICTURE"] = "picture";
})(inputType = exports.inputType || (exports.inputType = {}));
